### ISSUE TITLE
Address Union Types

### ISSUE THREAD

**Issue by mberry** [sphincs/sphincsplus#54]
###  Overview

Address operations are done at the byte level, yet represented by `uint32_t` arrays.

This results in a lot of casting in the functions, eg:

```C
void set_keypair_addr(uint32_t addr[8], uint32_t keypair)
{
#if SPX_FULL_HEIGHT/SPX_D > 8
        /* We have > 256 OTS at the bottom of the Merkle tree; to specify */
        /* which one, we'd need to express it in two bytes */
    ((unsigned char *)addr)[SPX_OFFSET_KP_ADDR2] = (unsigned char)(keypair >> 8);
#endif
    ((unsigned char *)addr)[SPX_OFFSET_KP_ADDR1] = (unsigned char)keypair;
}

````

### Alternative

Addresses are well suited as union types, this would result in cleaner code, improved readability and less casting.

### Implementation

```C
union address {
    uint32_t u32[8];
    unsigned char bytes[32];
};

void set_keypair_addr(union address addr, uint32_t keypair) {
#if SPX_FULL_HEIGHT/SPX_D > 8
    addr.bytes[SPX_OFFSET_KP_ADDR2] = (unsigned char)(keypair >> 8);
#endif
    addr.bytes[SPX_OFFSET_KP_ADDR1] = (unsigned char)keypair;
}

```

**Comment by sfluhrer** [comment]
I don't believe we currently reference addresses as uint32_t anywhere; hence if we were to change this, I suggest that, instead of a union, we use instead a bald (unsigned char [32]) type (or perhaps a typedef to make it more obvious).

History: the original code had the address as a uint32_t[8] type; however a) this required us to possibly convert endianness on every hash operation, and b) for SHA-256, we'd also do the compression, again, for every hash operation.  As an optimization, we converted to the current form (casting, and using manifest constants for the offsets, to account for the differences between the non-SHA2 and the SHA-2 formats); that way, we could feed the address structure directly to the hash function.  However, when we made this change, we declined to update the types throughout the code (as this would have caused a large code change); instead, we restricted the change to address.c (and the various parameter files)

Should we review this 'lets not cause a large code change' decision?

**Comment by sfluhrer** [comment]
Actually, I just found a place where it does treat the address as a uint32_t[8] type - shake-a64::hash_shakex2.c

In any case, there are *lots* of references to address structures throughout the code; the all currently use a uint32_t type.  If we were to make this change, we'd need to change all of them (and much of the indexing as well for x[248] logic); while each change is small, there are a lot of them.  My personal opinion: the benefit of this change (getting rid of a handful of casts) do not warrant the size of the code changes.

Hence, I'm closing this issue.
